### ISSUE TITLE
Streamer unable to connect to switch

### ISSUE THREAD

**Issue by NoPyroLGW** [DevL0rd/SkyNX#23]
Upon launching the PC Streamer and pressing "Start Streamer" the screen resolution is adjusted and the program searches for my switch, however it fails to find it and reverts my resolution, I ran ".\NxStreamingService.exe /ip yourswitchip /q 4" and got this out of the powershell window:

```CemuHook Server ID: 1239873223
Waiting for connection...
CemuHook: Listening at 0.0.0.0:26760
Connected to Switch!
Using CPU Encoding
37
Plugged in controller 1.
Plugged in controller 2.
ffmpeg version git-2020-04-22-2e38c63 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9.3.1 (GCC) 20200328
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --disable-w32threads --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
  libavutil      56. 42.102 / 56. 42.102
  libavcodec     58. 80.100 / 58. 80.100
  libavformat    58. 42.101 / 58. 42.101
  libavdevice    58.  9.103 / 58.  9.103
  libavfilter     7. 79.100 /  7. 79.100
  libswscale      5.  6.101 /  5.  6.101
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
[gdigrab @ 04c6df40] Capturing whole desktop as 1280x720x32 at (0,0)

ffmpeg version git-2020-04-22-2e38c63 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9.3.1 (GCC) 20200328
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --disable-w32threads --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
  libavutil      56. 42.102 / 56. 42.102
  libavcodec     58. 80.100 / 58. 80.100
  libavformat    58. 42.101 / 58. 42.101
  libavdevice    58.  9.103 / 58.  9.103
  libavfilter     7. 79.100 /  7. 79.100
  libswscale      5.  6.101 /  5.  6.101
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100

Plugged in controller 3.
Input #0, gdigrab, from 'desktop':
  Duration: N/A, start: 1588160697.722282, bitrate: 1769497 kb/s

    Stream #0:0: Video: bmp, bgra, 1280x720, 1769497 kb/s, 60 fps, 1000k tbr, 1000k tbn, 1000k tbc

3
Plugged in controller 4.
C:\Users\George\Downloads\SkyNXStreamer-win32-ia32\SkyNXStreamer-win32-ia32\resources\app\NxStreamingService\node_modules\ffi\lib\_foreign_function.js:55
      throw e
      ^

RangeError [ERR_OUT_OF_RANGE]: error setting argument 1 - The value of "value" is out of range. It must be >= -32768 and <= 32767. Received -1146958565.1988099
    at checkInt (internal/buffer.js:35:11)
    at writeU_Int16LE (internal/buffer.js:543:3)
    at Buffer.writeInt16LE (internal/buffer.js:686:10)
    at Object.set (C:\Users\George\Downloads\SkyNXStreamer-win32-ia32\SkyNXStreamer-win32-ia32\resources\app\NxStreamingService\node_modules\ref\lib\ref.js:898:52)
    at Object.set (C:\Users\George\Downloads\SkyNXStreamer-win32-ia32\SkyNXStreamer-win32-ia32\resources\app\NxStreamingService\node_modules\ref\lib\ref.js:487:10)
    at Object.alloc (C:\Users\George\Downloads\SkyNXStreamer-win32-ia32\SkyNXStreamer-win32-ia32\resources\app\NxStreamingService\node_modules\ref\lib\ref.js:521:13)
    at Object.proxy [as SetAxisRx] (C:\Users\George\Downloads\SkyNXStreamer-win32-ia32\SkyNXStreamer-win32-ia32\resources\app\NxStreamingService\node_modules\ffi\lib\_foreign_function.js:50:22)
    at VGen.setAxisR (C:\Users\George\Downloads\SkyNXStreamer-win32-ia32\SkyNXStreamer-win32-ia32\resources\app\NxStreamingService\node_modules\vgen-xbox\vgen-xbox.js:212:19)
    at handleControllerInput (C:\Users\George\Downloads\SkyNXStreamer-win32-ia32\SkyNXStreamer-win32-ia32\resources\app\NxStreamingService\main.js:211:8)
    at Socket.<anonymous> (C:\Users\George\Downloads\SkyNXStreamer-win32-ia32\SkyNXStreamer-win32-ia32\resources\app\NxStreamingService\main.js:502:5)```

I'm really not sure what the issue is *other* than it's probably me doing something stupid and easily fixable, any help would be greatly appreciated, if any more info is required just let me know and I can grab it, thank you.

**Comment by DevL0rd** [comment]
You need to update the switch app and the streamer to the same version.
And that bat file is a little outdated and missing newer args

**Comment by DevL0rd** [comment]
Also it seems that my packet can get jumbled sometimes in transmission and i didn't think to verify receipt, the latest version will fix all that jaz.
I will release it in a minute once i verify it works on someones 32 bit machine

**Comment by DevL0rd** [comment]
Here is the test streamer and the test app if you wanna try it:
[Streamer](https://drive.google.com/open?id=1a26quAGdBcK3bhRu8MUWZ-JD_VQIy7sU)
[App] (https://drive.google.com/open?id=1hVS92gD6pmYLZKh3OarMnSAvELETOq5B)

**Comment by DevL0rd** [comment]
Confirmed that this is fixed in latest release
