### ISSUE TITLE
Linux version?

### ISSUE THREAD

**Issue by SrSands** [DevL0rd/SkyNX#42]
Personally i don't play at all in Windows, I only use Manjaro to game.
Is there a plan for releasing a Linux version w/ all the features? 
I can test it if needed! Thanks.

**Comment by MrSnoozles** [comment]
#1

**Comment by SrSands** [comment]
I saw it, but as they talked mostly about a mac port i decided to open this issue. I don't see much problem emulating the controllers on linux as pretty much all controllers have kernel support or open source "drivers".

**Comment by thomascrha** [comment]
Its an electron app so building it on Linux shouldn't be to hard - it actually working properly is another issue. I'm going to give this a go - 
`npm i && npm run start`
and see what road blocks pop up

**Comment by y4my4my4m** [comment]
Only seem to work with nodev8 and also this is the result:
![image](https://user-images.githubusercontent.com/8145020/84687039-a8805700-af02-11ea-8470-2cb320233372.png)

**Comment by y4my4my4m** [comment]
Only seem to work with nodev8 and also this is the result:
![image](https://user-images.githubusercontent.com/8145020/84687039-a8805700-af02-11ea-8470-2cb320233372.png)

Obviously it's trying to launch an .exe on linux which is why its not working lol

**Comment by y4my4my4m** [comment]
Ok, I kind of got it to work after hacking away a bunch of the code.

Basically, you need to build the NxStreamingService using Nexe (like the build.bat but change to `linux-x86`). Change all references of `NxStreamingServices.exe` to without the `.exe`. 

Also comment out any reference to `Vgen` and `vgen` (xbox controller because windows only and uses DLL). As well as change `ffmpeg.exe` to your install of ffmpeg on linux ( `/usr/bin/ffmpeg` in my case)

Now I can connect and it doesn't crash, the touch controls work well, however the video streaming doesn't actually work. I'll keep investigating.

**Comment by mirh** [comment]
I think this is the trick
https://trac.ffmpeg.org/wiki/Capture/Desktop

**Comment by y4my4my4m** [comment]
@mirh yes..ive been trying to get the right ffmpeg output, `x11grab` seems to be the best solution but i still can't get to stream over TCP...probably just bad configuration. 

Will report back if I get it to work.

**Comment by y4my4my4m** [comment]
I got it to work!!!

Enabling `debug` in `settings.json` made it work.. Unsure why, but it works :)

**Comment by khalilgharbaoui** [comment]
I also see some instructions there for macOS maybe that could be a shortcut?

**Comment by khalilgharbaoui** [comment]
> I think this is the trick
> https://trac.ffmpeg.org/wiki/Capture/Desktop
Is this something we can use for macOS also?

Related to: #1

**Comment by y4my4my4m** [comment]
@khalilgharbaoui 

Here it is: 

https://github.com/y4my4my4m/SkyNX/commit/43bed97d65bdc223139ac0fdca34cf26e21c1784
Don't forget to change the `SkyNX-Streamer/settings.json` to `debug:true` as well.

> Is this something we can use for macOS also?

You can't use "Desktop" as it is for DirectShow (a Microsoft Windows thing).

For Linux I'm using x11grab, I'm not sure if macOS still uses X but it's probably something different nowadays, look for ffmpeg's screencapture parameters for macOS.

I'm quite sure my changes would work for macOS as well (although change linux-86 to something linux appropriate (look up nexe's parameters to build NxStreamingService)).

Obviously the remote control doesn't work. I was only interested in SkyNX as a way to use my Switch as a secondary monitor :)

**Comment by Zedjones** [comment]
Does it work with using the Joycons as a controller? @y4my4my4m

**Comment by y4my4my4m** [comment]
@Zedjones probably not, it uses the "xbox controller" on windows to detect input.

Probably doable by using this https://github.com/infusion/node-gamecontroller instead though. 
Looking at SkyNX source code (the app running on the switch) there dsnt seem to be anything xbox specific code, so this must all be done on the NxStreamingService side.

https://github.com/DevL0rd/SkyNX/blob/ff471143d545224a178cab63bab9a34411f2bcf6/SkyNX-Streamer/NxStreamingService/main.js#L9

This module should/could be replaced with `node-gamecontroller` (or something better)

**Comment by soripants** [comment]
@y4my4my4m 

I downloaded your fork and while I've got it built for linux, any time I hit the stream button I get this error. I did change over to debug in the settings.json:

`Error: /home/annie/Downloads/SkyNX-43bed97d65bdc223139ac0fdca34cf26e21c1784/SkyNX-Streamer/SkyNXStreamer-linux-ia32/resources/app/NxStreamingService/node_modules/robotjs/build/Release/robotjs.node: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (module.js:681:18)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/annie/Downloads/SkyNX-43bed97d65bdc223139ac0fdca34cf26e21c1784/SkyNX-Streamer/SkyNXStreamer-linux-ia32/resources/app/NxStreamingService/node_modules/robotjs/index.js:1:77)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)

streamerProcess process exited with code 1`

Any idea on what I can do to get this working?

**Comment by soripants** [comment]
@y4my4my4m 

I'm using your fork version including the debug thing. I've gotten it built for Linux but I'm getting a missing file. When I run npm install again in resources/app I get a version mismatch error, but when I go to install the proper version, I get missing file error again. Any ideas? What steps did you take to get this working, starting from scratch with your modified source.

**Comment by y4my4my4m** [comment]
@soripants What version of Node are you using? Seems to only compile if you're using node v8.

**Comment by robrichardson13** [comment]
Spent a little time and I was able to get this working on Mac (Monterey 12.5.1).

https://github.com/robrichardson13/SkyNX

Install `ffmpeg` via brew with `brew install ffmpeg`, then using node `v12.15.0` just run `npm install` in the `SkyNX-Streamer` directory and then `npm start` to run the application.

If the capture device is wrong for `ffmpeg`, run this to get the correct device index: `ffmpeg -f avfoundation -list_devices true -i ""`. Depending on the index, you might need to update `const screenDeviceIndex = '1';` in `main.js`.

**Notable changes:**
- Commented out the Xbox controller implementation using the `vgen-xbox` package
- Commented out the auto start functionality as that was crashing the app
- Added WSAD mapping to the joysticks, just comment out the calls to `handleLeftStick()` if you dont want this

**Comment by knives-repo** [comment]
> Spent a little time and I was able to get this working on Mac (Monterey 12.5.1).
> 
> https://github.com/robrichardson13/SkyNX
> 
> Install `ffmpeg` via brew with `brew install ffmpeg`, then using node `v12.15.0` just run `npm install` in the `SkyNX-Streamer` directory and then `npm start` to run the application.
> 
> If the capture device is wrong for `ffmpeg`, run this to get the correct device index: `ffmpeg -f avfoundation -list_devices true -i ""`. Depending on the index, you might need to update `const screenDeviceIndex = '1';` in `main.js`.
> 
> **Notable changes:**
> 
>     * Commented out the Xbox controller implementation using the `vgen-xbox` package
> 
>     * Commented out audio streaming
> 
>     * Commented out the auto start functionality as that was crashing the app
> 
>     * Added WSAD mapping to the joysticks, just comment out the calls to `handleLeftStick()` if you dont want this

I'm having trouble compiling with npm 12.15.0. I keep getting errors (electron etc.). Was wondering if you have an exportable build that can be downloaded?

**Comment by knives-repo** [comment]
Ok, turns out that the issue was the robotjs installation (the current package.json for some reason won't install it, so I installed the node manually from [here](https://github.com/csett86/robotjs)). The other issue is that I needed to delete the package-lock.json file and install electron manually, since electron wouldn't install through `npm i` either
